# Subsetting R Objects: Basics

## Basics

- [ returns an element of the same type as the source, meaning that it returns and array if the source was and array or a matrix if the source was a matrix
- [[ returns a single element
- $ extracts a element of a list by name 

In [18]:
x1 <- c("a","b","c","d","e","f","z","b","c")
print(x1[1])
print(x1[[1]])
print(x1[2:4])
print(x1[[4]])
# next will trow an error, 
# because [[ is only used to extract a single element
print(x1[[3:4]])

[1] "a"
[1] "a"
[1] "b" "c" "d"
[1] "d"


ERROR: Error in x1[[3:4]]: attempt to select more than one element in vectorIndex


In [19]:
# logical index
x2 <- c("a","b","c","d","e","f","z","b","c")
print(x2[x2 > "c"])

[1] "d" "e" "f" "z"


## Lists

In [28]:
x3 <- list(foo = 5:9, bar=0.2)
print(x3)
x3$foo
x3$bar
x3["bar"]
x3[["bar"]]

$foo
[1] 5 6 7 8 9

$bar
[1] 0.2



[1] 5 6 7 8 9

[1] 0.2

$bar
[1] 0.2

[1] 0.2

In [33]:
# this is how to extract multiple elements of a list
x4 <- list(foo = 5:9, bar=0.2, baz="hi")
x4
x4[c(1,3)]


$foo
[1] 5 6 7 8 9

$bar
[1] 0.2

$baz
[1] "hi"

$foo
[1] 5 6 7 8 9

$baz
[1] "hi"

In [39]:
# this is how we can access to an element of a list
# using a variable with computed index
x5 <- list(foo = 5:9, bar=0.2, baz=c("hi","bye"))
x5
name <- "baz"
# this will return a valid value
x5[[name]]
# this will return NULL because there is no index named "name"
x5$name
# this will return a valid calue
x5$baz

$foo
[1] 5 6 7 8 9

$bar
[1] 0.2

$baz
[1] "hi"  "bye"

[1] "hi"  "bye"

NULL

[1] "hi"  "bye"

In [47]:
x6 <- list(a=list(15,16,17),b=c(3.14, 2.81))
print(x6)
# extracting 16
print(x6[[c(1,2)]])
print(x6[[1]][[2]])
# extracting 2.81
print(x6[[c(2,2)]])

$a
$a[[1]]
[1] 15

$a[[2]]
[1] 16

$a[[3]]
[1] 17


$b
[1] 3.14 2.81

[1] 16
[1] 16
[1] 2.81


## Matrices

In [48]:
x7 <-matrix(7:12,2,3)
x7
x7[1,2]

[,1] [,2] [,3]
[1,] 7     9   11  
[2,] 8    10   12

[1] 9

In [49]:
x8 <-matrix(7:12,2,3)
x8[1,]
x8[,1]

[1]  7  9 11

[1] 7 8

In [54]:
# in this case the [ is dropping a dimension
# and we need it as a matrix
x9 <- matrix(1:8,4,6)
print(x9)
print(x9[3,4])
print(x9[3,4, drop=FALSE])

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    5    1    5    1    5
[2,]    2    6    2    6    2    6
[3,]    3    7    3    7    3    7
[4,]    4    8    4    8    4    8
[1] 7
     [,1]
[1,]    7


In [59]:
# here we are subsetting a matrix to get a matrix
x10 <- matrix(11:16,2,3)
print(x10)
print(x10[1,])
print(x10[1,,drop=FALSE])

     [,1] [,2] [,3]
[1,]   11   13   15
[2,]   12   14   16
[1] 11 13 15
     [,1] [,2] [,3]
[1,]   11   13   15
