# Vectorized Operations

In [10]:
# vector operations
x1 <- 5:9; x2 <- 2:6
print(x1)
print(x2)

print(x1 + x2)

print(x1 > 7)
print(x1 >= 7)
print(x1 == 7)
print(x1 * x2)
print(x1 / x2)

[1] 5 6 7 8 9
[1] 2 3 4 5 6
[1]  7  9 11 13 15
[1] FALSE FALSE FALSE  TRUE  TRUE
[1] FALSE FALSE  TRUE  TRUE  TRUE
[1] FALSE FALSE  TRUE FALSE FALSE
[1] 10 18 28 40 54
[1] 2.50 2.00 1.75 1.60 1.50


In [18]:
# matrix operations
x3 <- matrix(2:5, 2, 2)
x4 <- matrix(6:9, 2, 2)
print(x3)
print(x4)
print(x3 * x4) # element wise multiplication
print(x3 %*% x4) # true matrix multiplication

     [,1] [,2]
[1,]    2    4
[2,]    3    5
     [,1] [,2]
[1,]    6    8
[2,]    7    9
     [,1] [,2]
[1,]   12   32
[2,]   21   45
     [,1] [,2]
[1,]   40   52
[2,]   53   69
