# Loop Functions - Part I

## lapply

In [41]:
str(lapply)

function (X, FUN, ...)  


In [2]:
x1 <- list(a=1:5, b=rnorm(10))
x1

$a
[1] 1 2 3 4 5

$b
 [1]  0.05539918 -0.66226810  0.29912540  0.95017099  1.45284207 -0.65061433
 [7]  0.88975814 -1.85906335  0.09407448  0.66095498

In [4]:
lapply(x1, mean)

$a
[1] 3

$b
[1] 0.1230379

In [10]:
x2 <- 1:10
x2
lapply(x2, function(x) {x*2})

[1]  1  2  3  4  5  6  7  8  9 10

[[1]]
[1] 2

[[2]]
[1] 4

[[3]]
[1] 6

[[4]]
[1] 8

[[5]]
[1] 10

[[6]]
[1] 12

[[7]]
[1] 14

[[8]]
[1] 16

[[9]]
[1] 18

[[10]]
[1] 20

In [16]:
# in a matrix still funcion is apply element by element
# not by row or column
x3 <- matrix(1:9,nrow=3,ncol=3)
x3
lapply(x3, mean)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

[[6]]
[1] 6

[[7]]
[1] 7

[[8]]
[1] 8

[[9]]
[1] 9

In [20]:
x4 <- 1:5
lapply(x4, runif)

[[1]]
[1] 0.4897764

[[2]]
[1] 0.2584585 0.6010063

[[3]]
[1] 0.7139378 0.8727858 0.2769860

[[4]]
[1] 0.3175763 0.1631976 0.8626809 0.7501649

[[5]]
[1] 0.71234136 0.01122721 0.98890148 0.09134754 0.69391478

In [21]:
x5 <- 1:5
lapply(x5, runif, min=0, max=10)

[[1]]
[1] 9.943004

[[2]]
[1] 8.801872 7.765006

[[3]]
[1] 6.673934 4.529064 2.787203

[[4]]
[1] 0.2269786 7.9536030 3.8639622 6.9724869

[[5]]
[1] 3.479441 6.871780 7.905356 6.086229 5.989620

In [28]:
x6 <- list(a=matrix(1:4,2,2),b=matrix(1:6,3,2))
x6
lapply(x6, function(elt) elt[,1])

$a
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$b
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

$a
[1] 1 2

$b
[1] 1 2 3

## sapply

In [42]:
str(sapply)

function (X, FUN, ..., simplify = TRUE, USE.NAMES = TRUE)  


In [38]:
x7 <- list(a=1:4, b=rnorm(10), c=rnorm(20,1), d=rnorm(100,5))
x7_1 <- lapply(x7, mean) # this returns a list
x7_2 <- sapply(x7, mean) # this returns a vector
class(x7_1)
print(x7_1)
class(x7_2)
print(x7_2)

[1] "list"

$a
[1] 2.5

$b
[1] -0.2098414

$c
[1] 1.0499

$d
[1] 4.968357



[1] "numeric"

         a          b          c          d 
 2.5000000 -0.2098414  1.0499001  4.9683567 


## apply

In [46]:
str(apply)
?apply

function (X, MARGIN, FUN, ...)  


In [48]:
x8 <- matrix(rnorm(200),20,10)
apply(x8, 2, mean)
apply(x8, 1, sum)

[1] -0.05350417 -0.30388244 -0.09610692  0.43401278 -0.10250719 -0.22551650
 [7] -0.18065867  0.07058763 -0.10953517 -0.15477294

[1] -3.24824383  0.82733152 -0.14071377  2.26719373  8.28450797 -0.44743609
 [7] -4.15194920  4.72563786  0.09618339  1.09364786 -5.54220258  1.94474038
[13]  1.48594551 -6.67600089 -2.79773832 -7.81619820 -5.35483847 -3.94393616
[19]  3.78891273  1.16748465

In [51]:
x9 <- matrix(1:50, 5, 10)
x9
apply(x9, 2, mean) # mean by column
apply(x9, 1, sum) # sum by row

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1     6   11   16   21   26   31   36   41   46   
[2,] 2     7   12   17   22   27   32   37   42   47   
[3,] 3     8   13   18   23   28   33   38   43   48   
[4,] 4     9   14   19   24   29   34   39   44   49   
[5,] 5    10   15   20   25   30   35   40   45   50

[1]  3  8 13 18 23 28 33 38 43 48

[1] 235 245 255 265 275

In [56]:
# optimized functions to sums and means by cols or rows
x10 <- matrix(1:50, 5, 10)
rowSums(x10)
rowMeans(x10)
colSums(x10)
colMeans(x10)

[1] 235 245 255 265 275

[1] 23.5 24.5 25.5 26.5 27.5

[1]  15  40  65  90 115 140 165 190 215 240

[1]  3  8 13 18 23 28 33 38 43 48

In [57]:
# here another way to use apply with quantile function
x11 <- matrix(rnorm(200),20,10)
apply(x11, 1, quantile, probs=c(0.25, 0.75))

[,1]       [,2]      [,3]       [,4]       [,5]       [,6]       [,7]      
25% -0.6952584 0.1248712 0.01802172 -0.4592940 -1.3578267 -0.8440236 -0.5672652
75%  1.1036759 0.8684813 1.09530355  0.2941866  0.6108347  0.1168320  0.4701288
    [,8]       [,9]       [,10]      [,11]      [,12]      [,13]     
25% -0.1047369 -0.5846089 -1.2352011 -0.5342183 -0.3476227 -0.4618376
75%  0.7860125  0.6475137  0.6529744  0.7388011  0.8180397  0.2444147
    [,14]      [,15]       [,16]     [,17]      [,18]      [,19]      
25% -0.2634646 -0.08807319 0.1323911 -1.3271432 -0.5988209 -0.63278635
75%  0.9254039  0.54886999 0.8936973  0.2481777  0.7185843  0.02130018
    [,20]     
25% -0.9289163
75%  0.6177024

In [63]:
x12 <- array(rnorm(2*2*10),c(2,2,10))
print(x12)
print("-------------------------------------------------------")
# one way
x12_r1 <- apply(x12, c(1,2), mean)
print(x12_r1)
# another way
x12_r2 <- rowMeans(x12, dims=2)
print(x12_r2)
# x12_r1 and x12_r2 are exactly the same

, , 1

           [,1]       [,2]
[1,] -0.8477644  0.7830200
[2,]  1.4364662 -0.5053485

, , 2

          [,1]       [,2]
[1,] -1.065603  3.0226777
[2,] -1.060815 -0.7844098

, , 3

         [,1]       [,2]
[1,] 1.363663 -0.9511467
[2,] 1.124063 -0.1448004

, , 4

           [,1]       [,2]
[1,] 0.83318865 -0.4769876
[2,] 0.05925516 -0.1700926

, , 5

         [,1]       [,2]
[1,] 1.063944 -0.7926387
[2,] 1.563722  0.1785478

, , 6

          [,1]       [,2]
[1,] -1.417778 -0.0139881
[2,]  1.380291  1.3082452

, , 7

          [,1]      [,2]
[1,] 0.1908854 1.0304811
[2,] 1.6572910 0.3145319

, , 8

           [,1]        [,2]
[1,]  0.3365371 -0.08594746
[2,] -0.2282467  0.24616234

, , 9

           [,1]       [,2]
[1,] -0.6947372  0.4561168
[2,]  1.6241710 -0.9019014

, , 10

            [,1]       [,2]
[1,]  0.25554678 -0.2775102
[2,] -0.09161582  1.3812292

[1] "-------------------------------------------------------"
            [,1]       [,2]
[1,] 0.001788187 0.26940768
[2,] 0.74