# Matrices

In [2]:
m1 <- matrix(nrow=3, ncol=5)
print(m1)
class(m1)
dim(m1)
attributes(m1)

     [,1] [,2] [,3] [,4] [,5]
[1,]   NA   NA   NA   NA   NA
[2,]   NA   NA   NA   NA   NA
[3,]   NA   NA   NA   NA   NA


[1] "matrix"

[1] 3 5

$dim
[1] 3 5

In [4]:
# matrices are constructed column wise
m2 <- matrix(1:10, nrow=2, ncol=5)
print(m2)
class(m2)
dim(m2)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


[1] "matrix"

[1] 2 5

In [6]:
# what happend if input does not match dimesions?
m3 <- matrix(1:15, nrow=2, ncol=6)
print(m3)
class(m3)
dim(m3)

Warning message in matrix(1:15, nrow = 2, ncol = 6):
“data length [15] is not a sub-multiple or multiple of the number of rows [2]”

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    3    5    7    9   11
[2,]    2    4    6    8   10   12


[1] "matrix"

[1] 2 6

In [10]:
# creating a matrix from a vector
x1 = 1:15
print(x1)
class(x1)
dim(x1) <- c(3,5)
print(x1)
class(x1)

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15


[1] "integer"

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    4    7   10   13
[2,]    2    5    8   11   14
[3,]    3    6    9   12   15


[1] "matrix"

## Column binding and Row binding

In [12]:
x <- 1:3
y <- 10:12
cbind(x,y)
rbind(x,y)

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

In [ ]:
# what happe